[package]
name = "little-mage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

bevy = "0.12.0"
bevy_asset_loader = { version = "0.18.0", features = ["2d"] }
bevy_simple_text_input = "0.3.1"
bevy_ecs_ldtk = { git = "https://github.com/PraxTube/bevy_ecs_ldtk.git", branch = "feat/bevy-0.12" }
